apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-config
  namespace: pipeline
data:
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  ALLOWED_ORIGINS: "http://pipeline.local"
  VITE_API_URL: "http://pipeline.local/api"
