apiVersion: v1
kind: Secret
metadata:
  name: pipeline-secret
  namespace: pipeline
type: Opaque
stringData:
  JWT_SECRET: "changeme"
  DATABASE_URL: "postgresql://admin:yourpassword@postgres:5432/pipeline"
  DB_USER: "admin"
  DB_PASSWORD: "yourpassword"
